### ISSUE TITLE
Investigate "Maximum call stack size exceeded" on Magic Byte

### ISSUE THREAD

**Issue by thanpolas** [waldophotos/kafka-avro#10]
This appeared out of the blue, with a connected consumer but no actual topics defined to be consumed.

```
22:06:03.519Z ERROR waldo-core-api: GQL Error message -> Maximum call stack size exceeded
22:06:03.519Z ERROR waldo-core-api:
  GQL Error message -> RangeError: Maximum call stack size exceeded
      at Buffer.Uint8Array (native)
      at FastBuffer (buffer.js:11:5)
      at Buffer.slice (buffer.js:811:10)
      at allocate (buffer.js:173:23)
      at Function.Buffer.allocUnsafe (buffer.js:141:10)
      at new Buffer (buffer.js:78:19)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:23:13)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
      at Object.magicByte.toMessageBuffer (/app/node_modules/kafka-avro/lib/magic-byte.js:30:22)
```

**Comment by thanpolas** [comment]
closing due to inactivity, feel free to open if the problem persists.
