### ISSUE TITLE
kafkaAvro.init() causes ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by cryptogoth** [waldophotos/kafka-avro#15]
When I follow the quickstart example in the repo README, I get the following error and stacktrace:
```
> kafkaAvro.init().then(function() { console.log("Ready to use"); });
Promise {
  _bitField: 2097152,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _boundTo:
   noop {
     schemaRegistryUrl: 'localhost:8081',
     valueSchemas: {},
     keySchemas: {},
     schemaMeta: {},
     schemaTypeById: {} } }
> Unhandled rejection Error: connect ECONNREFUSED 127.0.0.1:80
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
```

**Comment by cryptogoth** [comment]
I suspect that there is a bare URL without a port number somewhere, and this defaults to using port 80.

This happens with both npm kafka-avro versions of 0.7.0 and 0.6.4.

**Comment by kcliffe** [comment]
Hi,

I am a novice with NodeJS. But my experience was that the url.resolve call in schema_registry.js (_fetchAllSchemaTopics) seems to drop the port - possibly due to this issue: 

https://stackoverflow.com/questions/16159782/node-js-resolving-url-with-port-included

I simply changed the url so it was fully qualified:
http://localhost:8081

And the sample works?

**Comment by kcliffe** [comment]
Not sure if this belongs here but as an addendum to the comment above the next thing I hit was that the connect method timed out. I suspect because I qualified both Uri's and the kafka broker Uri gets handed straight to the node-rdkafka lib as is (and they probably don't resolve the uri) so changing it back to localhost:9092 works.

I then got a null ref on "this" in the promise so... i changed the func to pass the consumer instance? 

This is my working sample:
```
var KafkaAvro = require('kafka-avro');

var kafkaAvro = new KafkaAvro({
    kafkaBroker: 'localhost:9092',
    schemaRegistry: 'http://localhost:8081',
});

// Query the Schema Registry for all topic-schema's 
// fetch them and evaluate them. 
kafkaAvro.init()
.then(function() {
    console.log('Ready to use');

    startConsumer();
});

function startConsumer() {
    kafkaAvro.getConsumer({
        'group.id': 'librd-test',
        'socket.keepalive.enable': true,
        'enable.auto.commit': true,
      })
        // the "getConsumer()" method will return a bluebird promise.
        .then(function(consumer) {
          // Perform a consumer.connect()
          return new Promise(function (resolve, reject) {
            consumer.on('ready', function() {
              resolve(consumer);
            });
      
            consumer.connect({}, function(err) {
              if (err) {
                reject(err);
                return;
              }
              resolve(consumer); // depend on Promises' single resolve contract.
            });
          });
        })
        .then(function(consumer) {
          // Subscribe and consume.
          var topicName = 'test-azure-Customer';
          consumer.subscribe([topicName]);
          consumer.consume();
          consumer.on('data', function(rawData) {
            console.log('data:', rawData);
          });
        });
}
```

**Comment by thanpolas** [comment]
closing due to inactivity, feel free to open if the problem persists.

**Comment by ervitis** [comment]
Good morning, we are having some troubles with it. We have a Kafka consumer inside a docker container and when I execute it, it throws that error.

We are using for development the Landoop kafka environment (https://github.com/Landoop/fast-data-dev). I don't understand why it needs to connect to port 80?

Regards!

**Comment by thanpolas** [comment]
Which version of kafka-avro are you using @ervitis ?

@ricardohbin any ideas?

**Comment by ricardohbin** [comment]
@ervitis whats your `schemaRegistry` url?

**Comment by ervitis** [comment]
Sorry, I was very busy to answer this. My mistake, I was using a wrong address.

Regards

**Comment by ricardohbin** [comment]
Can we close this issue? This is a behavior that occurs when the `schemaRegistry` doesn't have the full protocol in the url. Ex: `schema-registry.com`.

We can provide a guard clause or a better error message. What do you think @thanpolas ?
