### ISSUE TITLE
socket hangup error

### ISSUE THREAD

**Issue by ScottChapman** [waldophotos/kafka-avro#33]
SO, I am getting this when I connect:
```
{ Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at Socket.socketOnEnd (_http_client.js:409:23)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET',
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.15.3' },
     method: 'get',
     url: 'http://10.3.0.42:18082/subjects',
     data: undefined },
  response: undefined }
```

My code looks like:
```
var KafkaAvro = require('kafka-avro');
var options = {
	  'group.id': 'kafka',
	  'ssl.ca.location': "./secrets/ca.crt",
	  'ssl.certificate.location': "./secrets/cert.pem",
	  'ssl.key.location': "./secrets/cert-key.pem",
	  'ssl.key.password': "changeit",
	  'security.protocol': "ssl",
	  'metadata.broker.list': "kafka-0.kafka.default:9093"
};

var topicName = 'actionable-event-topic';

var kafkaAvro = new KafkaAvro({
	kafkaBroker: 'kafka-0.kafka.default:9093',
	schemaRegistry: 'http://10.3.0.42:18082'
});

kafkaAvro.init().then(function() {
	console.log("Kafka Avro Ready to go!");
}).catch(err => {
	console.dir(err);
});
```

Not sure if this matters, but I am using SSL on the brokers

**Comment by ScottChapman** [comment]
Just a little more info. I do have a `ca.cert` file I need to use. So the following CURL command works:
` curl -X GET -i --cacert secrets/ca.crt https://schema-registry:18082/subjects`
