### ISSUE TITLE
librdkafka.sp.1 not found

### ISSUE THREAD

**Issue by philippschladitz** [waldophotos/kafka-avro#38]
I was trying to use kafka-avro for the first time but just requiring the package fails with this error message:

Code:
`const KafkaAvro = require('kafka-avro');`

Error:
Error: librdkafka.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)

**Comment by thanpolas** [comment]
please provide more details, what platform, OS version, node version, npm version did this happen?

Most likely it's due to a problem compiling the required binaries, uninstall and reinstall kafka-avro and observe the building logs.

**Comment by giannisp** [comment]
@philippschladitz is `libsasl2-dev` present on the Ubuntu installation?

**Comment by philippschladitz** [comment]
I tried it again with a fresh ubuntu and libsasl2-dev. 
The error persists:
/home/philipp/project/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: librdkafka.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at bindings (/home/philipp/project/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/philipp/project/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/philipp/project/node_modules/node-rdkafka/lib/client.js:14:13)

**Comment by Amiko** [comment]
@philippschladitz 
git clone https://github.com/edenhill/librdkafka && cd librdkafka && git checkout 52c0a71e40a288307b526acd78b8d60c65bcc505 && ./configure && make && make install && ldconfig

Try this.

**Comment by philippschladitz** [comment]
@Amiko thanks. This is working. Is it possible to update the npm package?

**Comment by Amiko** [comment]
@philippschladitz I'm not a contributor to this project. I advice against using this library. It's no longer supported and it simply crashed my node application. Use kafka-node and write your own logic for avro SR and validation. :(

**Comment by thanpolas** [comment]
Thanks @Amiko for the help, librdkafka is provided by the library we wrap around, "node-rdkafka". @ricardohbin maybe it's worth the effort to check with them if they have updated their librdkafka and if not bug them to?

**Comment by ricardohbin** [comment]
@thanpolas sure, I will check.

@Amiko , what version crashed your application? I am asking because I use this lib in production with large amount of data too. Maybe, you found a bug

**Comment by Amiko** [comment]
@ricardohbin I believe it was latest 1.0.4. 
I was building an image with docker which would work just fine in local container but it would crash without ANY Logs, whenever I deployed. I believe it has something to do with librdkafka most probably it had issues resolving core libraries. Even though I fixed local issues with librdkafa by installing and configuring it manually it wouldn't fix crashing node app on the server.
Hope this info somehow helps.

**Comment by ricardohbin** [comment]
@Amiko What's your dockerfile? And where you deploy it? This Dockerfile sample works perfectly - both in to build in CI (circleCI) and to deploy it in production (kubernetes cluster)

```
FROM mhart/alpine-node:8.9.1

RUN apk --no-cache add \
      bash \
      g++ \
      ca-certificates \
      lz4-dev \
      musl-dev \
      cyrus-sasl-dev \
      openssl-dev \
      make \
      python

RUN apk add --no-cache --virtual .build-deps gcc zlib-dev libc-dev bsd-compat-headers py-setuptools bash

RUN mkdir -p /usr/local/app

WORKDIR /usr/local/app

COPY . /usr/local/app

RUN npm install node-rdkafka

RUN npm install

CMD ["npm", "start"]

```

**Comment by Amiko** [comment]
@ricardohbin I had something like this. But I removed git clone part when I changed to kafka-node library.

`ROM node:9

ENV BUILD_PATH /opt/app
ENV NODE_ENV production

RUN git clone https://github.com/edenhill/librdkafka && cd librdkafka && git checkout 52c0a71e40a288307b526acd78b8d60c65bcc505 && ./configure && make && make install && ldconfig

RUN mkdir -p $BUILD_PATH
WORKDIR $BUILD_PATH

ADD ./ $BUILD_PATH

EXPOSE 9090
HEALTHCHECK CMD curl --fail http://localhost:9090/health || exit 1

ENTRYPOINT [ "npm", "start" ]`
